### ISSUE TITLE
Incorrect license in package.json

### ISSUE THREAD

**Issue by nzakas** [kemitchell/spdx-exceptions.json#1]
The repository says that this code is MIT licensed, but package.json says it's creating commons licensed. Can update package.json to say MIT?

**Comment by kemitchell** [comment]
The SPDX spec itself is CC-BY licensed, and so is this package.

Not sure why a copy of the MIT License was included. Removed in 7d437e913bcb0cbad78e709101587e24778694a8.

Thanks for pointing this out!

**Comment by kemitchell** [comment]
Landed in 1.0.3.
