### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by sfakir** [kemitchell/spdx-exceptions.json#4]
Hi,
by making use of "CC-BY-3.0" you make your package unusable in almost any context. NPM packages have usually MIT/BSD license.

**Comment by kemitchell** [comment]
Simon,

 The SPDX spec is licensed CC-BY-3.0. To the extent there is US copyright in the SPDX exceptions, I think that copyright is The Linux Foundation's, not mine, with no additional copyrightable work of authorship in my simple transformation to JSON. You should do your own research and come to your own conclusion.

I [fully admit](https://github.com/npm/npm/pull/8179#issuecomment-98931828) that MIT- and BSD-style licenses are the norm on npm's public repository. But I also strongly disagree with your assessment of CC-BY-3.0. There is tons of -BY-licensed material on the web in common commercial and personal use.
