### ISSUE TITLE
Relicensing

### ISSUE THREAD

**Issue by TigerC10** [kemitchell/spdx-exceptions.json#5]
The Creative Commons Website expresses:
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering [licenses made available](https://www.gnu.org/licenses/license-recommendations.html) by the [Free Software Foundation](https://www.fsf.org/) or [listed as “open source”](https://opensource.org/licenses) by the [Open Source Initiative](http://www.opensource.org/).
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.
> 
> Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is [one-way compatible](https://creativecommons.org/compatiblelicenses) with the [GNU General Public License version 3.0](https://www.gnu.org/copyleft/gpl.html) (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two. There are special considerations required before using this compatibility mechanism. Read more about it [here](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3).
> 
> Also, the CC0 Public Domain Dedication **is** GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.
> 
> While we recommend against using a CC license on software itself, CC licenses may be used for software documentation, as well as for separate artistic elements such as game art or music.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

It'd be great if this particular package could be licensed under a more software-oriented license like `MIT` (preferred), `Apache-2.0 ` (safest/best option), or `LGPL-3.0`, or even `GPL-3.0`.

The Creative Commons license that SPDX is released under doesn't carry the same "you must license your thing under the same license as this thing you're borrowing" like the GPL/LGPL licenses do.  #4 didn't mention this fact.  So long as you've attributed correctly (as you have in README.md), you can re-license this particular package.  To be totally safe, use the `Apache-2.0` or `LGPL-3.0` licenses to require the attribution in much the same way.

**Comment by kemitchell** [comment]
> It'd be great if this particular package could be licensed under a more software-oriented license

This package isn't software. It's a data file. Basically, a list of identifiers. None of which did I choose.

> So long as you've attributed correctly (as you have in README.md), you can re-license 

I disagree. See section 4 of CC-BY.

**Comment by TigerC10** [comment]
Section 4 of CC-BY states:
> This Section 4(a) applies to the Work as incorporated in a Collection, but this does not require the Collection apart from the Work itself to be made subject to the terms of this License

So uh, yeah, your JSON file isn't bound to the CC-BY just because you're using something licensed by CC-BY.

**Comment by kemitchell** [comment]
My JSON file embodies no independent copyrightable work. [See my note in `README`.](https://github.com/jslicense/spdx-exceptions.json#this-package)

CC-BY isn't my license. It's the Linux Foundation's.
