### ISSUE TITLE
Switch to CC0-1.0 or CC-BY-4.0?

### ISSUE THREAD

**Issue by igoradamenko** [kemitchell/spdx-exceptions.json#7]
Hey, @kemitchell!

I've noticed this dependency in the list of installed and I was curious about the reasons to use CC-BY-3.0. [It's not marked as FSF Free](https://spdx.org/licenses/) on SPDX website, so I'm not sure that I can use it in my project, because CC-BY-3.0 is possibly does not work properly in my country.

So I went to the issues and found out that all of them are about the license _(here should be harold hiding pain meme jpeg)_. 

Then I went to the SPDX repos, trying to find their licenses. And here is what I found there:

https://github.com/spdx/license-list-XML/commit/912cb3943b5e32de99e372dbe2df440e578362ef

And it looks like the list you have in index.json is the list of filenames stored here:

https://github.com/spdx/license-list-XML/tree/master/src/exceptions

So, I decided to ask you. Is it possible to relicense the repo due to the fact that the same info is stored in SPDX repo under CC0-1.0?

If not, is it possible to use CC-BY-4.0 instead of 3.0? 4.0 works fine in my country and is also FSF Free.

**Comment by kemitchell** [comment]
Please read the README.

**Comment by igoradamenko** [comment]
@kemitchell, yeah, I did. I understand that you've built the package by copy-pasting the IDs of the exceptions from the SPDX spec. Due to the fact that the spec itself is licensed by CC-BY-3.0 you have to respect it and license this package in the same way.

What I was talking about is the way to find a workaround. Instead of copying the IDs from the spec itself, copy them from the [spdx/license-list-XML](https://github.com/spdx/license-list-XML), which is [licensed by the SPDX people as CC0-1.0](https://github.com/spdx/license-list-XML/pull/710).

From my point of view it is a way to use CC0-1.0 for this package. Am I wrong?
